name: golangci-lint

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/setup-go@bfdd3570ce990073878bf10f6b2d79082de49492
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
      - name: golangci-lint
        uses: golangci/golangci-lint-action@b517f99ae23d86ecc4c0dec08dcf48d2336abc29
        with:
          version: latest
